[package]
name = "exfac-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
serde = "1.0.145"
serde_json = "1.0.85"

tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter", "fmt"] }
tracing = "0.1"

# cli
clap = { version = "3.0.10", features = [
    "derive",
    "env",
    "unicode",
    "wrap_help",
] }
clap_complete = "3.0.4"
uuid = "1.1.2"
tokio = { version = "1.21.1", features = ["macros"] }
dotenv = "0.15.0"
yansi = "0.5.1"
eyre = "0.6.8"

[build-dependencies]
vergen = "7.4.2"
